### ISSUE TITLE
Add gg and G from vim for scrolling to start/end faster

### ISSUE THREAD

**Issue by adisidev** [nchudleigh/homerow#130]
**Is your feature suggestion related to a problem? Please describe.**
I'm always frustrated when I need to scroll all the way to the top or bottom of a document.

**Describe the solution you'd like**
VIM solves this by providing `gg` and `G`. It would helpful to implement the same for homerow scrolling!

**Describe alternatives you've considered**
I suppose I could use page up, or page down, and/or map gg and G to scroll up and down myself using say Karabiner Elements, but it would be nice to have this in-built, and I believe it should not be too tough!

**Comment by kaiguang** [comment]
Hey @adisidev this feature is already in the app, have you tried it?

**Comment by adisidev** [comment]
Indeed, my bad! It's already there!
