### ISSUE TITLE
option to customize letter usage

### ISSUE THREAD

**Issue by inthegreenwild** [nchudleigh/homerow#37]
**Is your feature suggestion related to a problem? Please describe.**

I would like better customization of the letter combinations. For example, sometimes I want to make the characters larger than the current max font size depending on my desk setup or apps I am using. I also would like to change the colors for better contrast. 

**Describe the solution you'd like**

I would  like if we could further customize the letter bubbles that show up in terms of size, color, and maybe even font style. 

**Describe alternatives you've considered**

**Comment by dexterleng** [comment]
> I want to make the characters larger than the current max font size depending on my desk setup or apps I am using

Hmm this font size isn't big enough?

![CleanShot 2023-01-29 at 23 16 43@2x](https://user-images.githubusercontent.com/34204380/215336036-71e0a7d0-90c7-4728-a848-e239b1944b34.png)

>  I also would like to change the colors for better contrast.

I would like to add a curated set of styles. What colors would you like to see specifically? I feel like the contrast is already pretty good.

**Comment by inthegreenwild** [comment]
Unfortunately yes I have to adjust the resolution on my work monitor to see numbers at the edge of the screen. I have a hard time distinguishing several letters like N, M, D, G. 

The colors work ok on a dark background but are harder to process when the monitor background bright. The gradient I think makes things worse. An easy way to validate contrast is through something like https://color.adobe.com/create/color-contrast-analyzer The current colors at the darkest (the least readable) part of the gradient has a contrast ratio of about 5:1. Which is good, but it would be nice if a stronger contrast was offered and if you can flip to a dark background with light text depending on which applications you're using. 

Here's an example of tweaking the existing colors: 

![Screen Shot 2023-01-31 at 3 46 18 PM](https://user-images.githubusercontent.com/8966510/215890826-a6aedb37-b82c-4f82-891c-714c6dbc2c3e.png)


I think any of the following would be nice to haves for accessibility: 
- ability to change the font family or weight
- ability to scale up the size a bit more 
- ability to choose from high contrast color combos (contrast of 7 or greater) with both light and dark backgrounds with no gradient. Personally I think anything above 10:1 is best but I got the number 7 based on WCAG AAA compliance recommendations. 
- Some color combinations (as well as the inverse) might be: 
121212 + FFFFFF
FCFCFC + 121212
FFFFFF + 121212
F7FBFC + 121212
FFFDE8 + 121212

**Comment by dexterleng** [comment]
@inthegreenwild I see. Homerow needs to be more accessible - it would be ironic if an app that depends on other apps being accessible is itself not accessible. I will need to read up more on the topic.

**Comment by dexterleng** [comment]
W.R.T the contrast, do you enable "Increase Contrast" in Settings? Homerow's labels are not aware of this option, but if you did use it - I can add a high contrast version of labels really quickly (without implementing a configuration panel).

![CleanShot 2023-02-03 at 13 00 20@2x](https://user-images.githubusercontent.com/34204380/216516362-8e11da4b-c90a-466b-a625-51e5a0f7bce0.png)

**Comment by inthegreenwild** [comment]
I've not tried that setting before but If adding a contrast system label is something simple to do on your end it sounds like a great option until a configuration panel is available. 

Appreciate you looking into this! I'm really enjoying homerow so far and it's put me one step close to ditching the mouse entirely. Happy to help test anything if needed.

**Comment by dexterleng** [comment]
@inthegreenwild Here is a custom build that shows a high contrast variant when 'Increase Contrast' is enabled. Let me know your thoughts!

[homerow-high-contrast.zip](https://github.com/dexterleng/homerow/files/10610232/homerow-high-contrast.zip)

![CleanShot 2023-02-05 at 12 43 46](https://user-images.githubusercontent.com/34204380/216802037-dbd9d701-7e29-434c-910e-3db783c67c3d.png)

19.4:1 ratio:
![CleanShot 2023-02-05 at 12 43 22](https://user-images.githubusercontent.com/34204380/216802021-d27fa468-bc00-4b38-a6f8-052229caa151.png)

**Comment by dexterleng** [comment]
Shipped this in Alpha 17.

**Comment by inthegreenwild** [comment]
I've been using it for the past two days and it does improve legibility a bit, thank you! I think in the future it would still be really beneficial to be able to customize the font family/style and colors (like inverted colors for usage on primarily light-themed applications).

**Comment by nchudleigh** [comment]
@inthegreenwild In version 1.0 I released two new themes (dark and light) They might improve your experience with the legibility of the app, personally really like the light theme :)
