### ISSUE TITLE
Support Notion

### ISSUE THREAD

**Issue by p-iknow** [nchudleigh/homerow#86]
**Describe the bug**

"I use Notion quite frequently, but I'm experiencing a lot of inconvenience because homerow doesn't work in Notion."

**Screenshots / video**

<img width="1235" alt="image" src="https://github.com/dexterleng/homerow/assets/35516239/740f7a09-8e9f-41b5-91e3-3122b70ad6e1">

**Steps to reproduce the bug**

1. Go to Notion desktop app 
2. run home row (ctrl + f)
3. you can see the error that not to show alphabet label to the element

**Comment by emilbryggare** [comment]
I'm quite sure this worked for me before, however getting the same results as @p-iknow now

**Comment by evelant** [comment]
@dexterleng any chance this could get prioritized? I rely heavily on Notion for work. No HomeRow support is a huge bummer. It's one of the only apps I have to reach for my mouse with anymore.

**Comment by ryneb** [comment]
It used to work for me, too. Miss using it!

**Comment by aiba** [comment]
I just discovered homerow and am LOVING this software overall.  Only way it could be better is if it supported Notion as well, so +1 to this issue.

**Comment by ztrawhcs** [comment]
Same here! I am really liking HomeRow and I was devastated to see it doesn't work in Notion considering that's where I spend much of my workday. :(

**Comment by yulonglin** [comment]
Frustrated by this issue too! @dexterleng any chance you could include support for Notion? 😅

**Comment by p-iknow** [comment]
it is resolved in v1.0 thanks to @dexterleng 
![image](https://github.com/nchudleigh/homerow/assets/35516239/d7549b22-2cea-4243-a227-9c5e9e5d1072)

**Comment by nchudleigh** [comment]
Fixed in v1.0!

To update to v1.0:

• Download new version from https://homerow.app
• Remove all accessibility permissions from old version (bundle ID and signing authority had to change from Dexter's to mine)
• Start up Homerow
• Add accessibility permissions
• Activate your license if you have one

Cheers!

**Comment by kdt-hata** [comment]
I installed the app from homerow v1.3.0  through homebrew yesterday and it didn't work on my Notion Desktop app....
<img width="1440" alt="Screenshot 2025-01-13 at 14 56 40" src="https://github.com/user-attachments/assets/d4ec4399-2141-49a5-b31b-b4cd0b0aade5" />

Can I ask for advice, please?
